import { z } from 'zod'

const COLLECTION_TYPES = ['COLLECTION', 'WISHLIST'] as const

export const comicFormSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  synopsis: z.string().nullable(),
  issueNumber: z.string().nullable(),
  volume: z.string().nullable(),
  year: z.number().int().positive().nullable(),
  coverDate: z.string().nullable(),
  barcode: z.string().nullable(),
  legacyNumber: z.string().nullable(),
  variantNumber: z.string().nullable(),
  coverLetter: z.string().nullable(),
  era: z.string().nullable(),
  language: z.string().nullable(),
  country: z.string().nullable(),
  typeOfComic: z.string().nullable(),
  numberOfPages: z.number().int().positive().nullable(),
  printing: z.string().nullable(),
  coverPrice: z.number().min(0).nullable(),
  coverPriceCurrency: z.string().nullable(),
  read: z.boolean(),
  preordered: z.boolean(),
  forSale: z.boolean(),
  quantity: z.number().int().min(1),
  condition: z.string().nullable(),
  storageLocation: z.string().nullable(),
  loanedTo: z.string().nullable(),
  signedBy: z.string().nullable(),
  personalRating: z.string().nullable(),
  purchasePrice: z.number().min(0).nullable(),
  purchasePriceCurrency: z.string().nullable(),
  purchaseDate: z.string().nullable(),
  purchasedFrom: z.string().nullable(),
  collectionWishlist: z.enum(COLLECTION_TYPES).nullable(),
  notes: z.string().nullable(),
  gradedBy: z.string().nullable(),
  gradedRating: z.string().nullable(),
  gradedLabelType: z.string().nullable(),
  gradedSerialNumber: z.string().nullable(),
  graderNotes: z.string().nullable(),
  pageQuality: z.string().nullable(),
  publisherName: z.string().nullable(),
  seriesName: z.string().nullable(),
  creatorsWriter: z.array(z.string()),
  creatorsArtist: z.array(z.string()),
  creatorsPenciller: z.array(z.string()),
  creatorsInker: z.array(z.string()),
  creatorsColorist: z.array(z.string()),
  creatorsCoverArtist: z.array(z.string()),
  creatorsLetterer: z.array(z.string()),
  creatorsEditor: z.array(z.string()),
  creatorsCreatedBy: z.array(z.string()),
  characters: z.array(z.string()),
  storyArcs: z.array(z.string()),
  genres: z.array(z.string()),
  subgenres: z.array(z.string()),
})

export type ComicFormValues = z.infer<typeof comicFormSchema>
